apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 6
  selector:
    matchLabels:
      app: vote
  strategy: {}
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: schoolofdevops/vote:v6
        name: vote
        resources: {}
status: {}
